version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: wallet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wallet_system
      MYSQL_USER: wallet_user
      MYSQL_PASSWORD: wallet_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - wallet-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Cache & Queue
  redis:
    image: redis:7-alpine
    container_name: wallet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wallet-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  # Wallet System API
  api:
    build: .
    container_name: wallet-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASE=wallet_system
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_URL=redis://redis:6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - wallet-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  redis_data:

networks:
  wallet-network:
    driver: bridge 